"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from owasp_nest.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class ChapterTypedDict(TypedDict):
    r"""Schema for Chapter (minimal fields for list display)."""

    created_at: datetime
    key: str
    name: str
    updated_at: datetime
    latitude: NotRequired[Nullable[float]]
    longitude: NotRequired[Nullable[float]]


class Chapter(BaseModel):
    r"""Schema for Chapter (minimal fields for list display)."""

    created_at: datetime

    key: str

    name: str

    updated_at: datetime

    latitude: OptionalNullable[float] = UNSET

    longitude: OptionalNullable[float] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["latitude", "longitude"])
        nullable_fields = set(["latitude", "longitude"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
