"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .issuestate import IssueState
from datetime import datetime
from owasp_nest.types import BaseModel, Nullable, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import TypedDict


class MilestoneDetailTypedDict(TypedDict):
    r"""Detail schema for Milestone (used in single item endpoints)."""

    created_at: datetime
    number: int
    state: IssueState
    r"""Issue state choices."""
    title: str
    updated_at: datetime
    url: str
    body: str
    closed_issues_count: int
    due_on: Nullable[datetime]
    open_issues_count: int


class MilestoneDetail(BaseModel):
    r"""Detail schema for Milestone (used in single item endpoints)."""

    created_at: datetime

    number: int

    state: IssueState
    r"""Issue state choices."""

    title: str

    updated_at: datetime

    url: str

    body: str

    closed_issues_count: int

    due_on: Nullable[datetime]

    open_issues_count: int

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
