"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from owasp_nest.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class RepositoryDetailTypedDict(TypedDict):
    r"""Detail schema for Repository (used in single item endpoints)."""

    created_at: datetime
    name: str
    updated_at: datetime
    commits_count: int
    contributors_count: int
    forks_count: int
    open_issues_count: int
    stars_count: int
    description: NotRequired[Nullable[str]]


class RepositoryDetail(BaseModel):
    r"""Detail schema for Repository (used in single item endpoints)."""

    created_at: datetime

    name: str

    updated_at: datetime

    commits_count: int

    contributors_count: int

    forks_count: int

    open_issues_count: int

    stars_count: int

    description: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["description"])
        nullable_fields = set(["description"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
